# Generated by Django 5.0.6 on 2024-06-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crewmember',
            old_name='position',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='crewmember',
            old_name='first_name',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='crewmember',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='crewmember',
            name='last_name',
        ),
    ]
